"""
SBOM format-specific filtering strategies for better maintainability.
"""

from abc import ABC, abstractmethod
from typing import Dict, List
from ..models import SoftwareComponent
from .filters import ComponentFilter


class SBOMFilterStrategy(ABC):
    """Abstract base class for SBOM format-specific filtering strategies."""
    
    def __init__(self):
        self.component_filter = ComponentFilter(sbom_format=self.get_format_name())
    
    @abstractmethod
    def get_format_name(self) -> str:
        """Return the SBOM format name."""
        pass
    
    @abstractmethod
    def should_exclude_component(self, component: SoftwareComponent) -> bool:
        """Determine if a component should be excluded."""
        pass
    
    def filter_components(self, components: List[SoftwareComponent]) -> List[SoftwareComponent]:
        """Filter components based on format-specific logic."""
        return [c for c in components if not self.should_exclude_component(c)]


class CycloneDXAppIdentifierFilter(SBOMFilterStrategy):
    """Filter for CycloneDX SBOMs generated by app_identifier.sh"""
    
    def get_format_name(self) -> str:
        return "CycloneDX"
    
    def should_exclude_component(self, component: SoftwareComponent) -> bool:
        """Exclude only OS/kernel components - keep system packages for analysis."""
        component_dict = {
            "name": component.name,
            "version": component.version,
            "type": component.component_type,
            "properties": component.properties
        }
        
        # Keep system packages (RPM/DEB) - they are the main content of app_identifier SBOMs
        if self.component_filter.is_system_package(component_dict):
            return False
        
        return self.component_filter.is_os_kernel_component(component_dict)


class CycloneDXThirdPartyFilter(SBOMFilterStrategy):
    """Filter for CycloneDX SBOMs from third-party tools like Syft."""
    
    def get_format_name(self) -> str:
        return "CycloneDX"
    
    def should_exclude_component(self, component: SoftwareComponent) -> bool:
        """Keep system packages, exclude only OS/kernel components."""
        component_dict = {
            "name": component.name,
            "version": component.version,
            "type": component.component_type,
            "properties": component.properties
        }
        
        # Keep system packages, exclude only OS/kernel components
        if self.component_filter.is_system_package(component_dict):
            return False  # Keep system packages
        
        return self.component_filter.is_os_kernel_component(component_dict)


class SPDXFilter(SBOMFilterStrategy):
    """Filter for SPDX format SBOMs."""
    
    def get_format_name(self) -> str:
        return "SPDX"
    
    def should_exclude_component(self, component: SoftwareComponent) -> bool:
        """Exclude only OS/kernel components."""
        component_dict = {
            "name": component.name,
            "version": component.version,
            "type": component.component_type,
            "properties": component.properties
        }
        
        return self.component_filter.is_os_kernel_component(component_dict)


class SyftFilter(SBOMFilterStrategy):
    """Filter for Syft format SBOMs."""
    
    def get_format_name(self) -> str:
        return "Syft"
    
    def should_exclude_component(self, component: SoftwareComponent) -> bool:
        """Exclude only OS/kernel components."""
        component_dict = {
            "name": component.name,
            "version": component.version,
            "type": component.component_type,
            "properties": component.properties
        }
        
        return self.component_filter.is_os_kernel_component(component_dict)


def get_filter_strategy(sbom_format: str, sbom_source: str) -> SBOMFilterStrategy:
    """Factory function to get appropriate filter strategy."""
    if sbom_format == "CycloneDX":
        if sbom_source == "app_identifier":
            return CycloneDXAppIdentifierFilter()
        else:
            return CycloneDXThirdPartyFilter()
    elif sbom_format == "SPDX":
        return SPDXFilter()
    elif sbom_format == "Syft":
        return SyftFilter()
    else:
        raise ValueError(f"Unsupported SBOM format: {sbom_format}")